name: Build from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_HEAD_REF##*/}
    - name: Build the Docker images
      run: |
        export GIT_TAG_NAME=${GITHUB_HEAD_REF##*/}
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make dockerimage
        make dockerpush
