name: Build image from release tag

on:
  release:
    types:
      - published

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -p bugs -p unused --timeout=10m

      - name: Build the Docker images
        run: |
          export GIT_TAG_NAME=${GITHUB_REF##*/}
          make dockerimage
          make dockerpush
